[package]
name = "thrushc"
description = "The Compiler for Thrush Programming Language."
license = "GPL-3.0"
license-file = "LICENSE.txt"
version = "1.0.0"
edition = "2024"
authors = ["DevCheckOG > https://github.com/DevCheckOG"]

[dependencies]
colored = "3.0.0"
ahash = "0.8.11"
lazy_static = "1.5.0"

llvm-sys = { path = "crates/llvm-sys-v170.0.0", features = ["force-static"] }
inkwell = { path = "crates/inkwell-v0.5.0", features = [
    "llvm17-0",
    "llvm17-0-force-static"
]}

[profile.dev]
incremental = true

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
panic = "abort"
debug = false
strip = true
incremental = true