[package]
name = "thrushc"
description = "The AOT Compiler for Thrush Programming language."
version = "1.0.0"
edition = "2024"
authors = ["DevCheckOG [https://github.com/DevCheckOG]"]

[dependencies]
stylic = "0.2.3"
ahash = "0.8.11"
lazy_static = "1.5.0"
inkwell = { version = "0.5.0", features = [
    "llvm17-0",
    "llvm17-0-force-static",
]}
llvm-sys = { version = "170.0.0", features = ["force-static"] }

[build-dependencies]
num_cpus = "1.16.0"

[profile.dev]
incremental = true

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
panic = "abort"
debug = false
strip = true
incremental = true