[package]
name = "thrushc"
description = "The Compiler for Thrush Programming Language."
license = "GPL-3.0"
version = "1.0.0"
edition = "2024"
authors = ["Kevin Benavides <https://github.com/DevCheckOG>"]
readme = "README.md"
build = "build.rs"

[build-dependencies]
isahc = { version= "1.7.2", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
lazy_static = "1.5.0"
serde_json =  "1.0.140"
colored = "3.0.0"

[dependencies]
colored = "3.0.0"
ahash = "0.8.11"
lazy_static = "1.5.0"
rand = "0.9.1"

llvm-sys = { path = "wrappers/llvm/llvm-sys", features = ["force-static"] }
inkwell = { path = "wrappers/llvm/inkwell", features = [
    "llvm17-0",
    "llvm17-0-force-static"
]}
lld = { path = "wrappers/llvm/lld" }

[profile.dev]
incremental = true

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
panic = "abort"
debug = false
strip = true
incremental = true
