[package]
name = "lld"
version = "1.0.0"
edition = "2024"
build = "build.rs"
description = "LLVM Linker bindings for Thrush Programming Language."
authors = ["Kevin Benavides <https://github.com/DevCheckOG>"]

[build-dependencies]
lazy_static = "1.5.0"
cc = "1.2.10"
colored = "3.0.0"